---
title: "Airbnb dashboard"
author: "Boxuan Li"
date: "11/1/2017"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
navbar:
    left:
    - text: "Home"
      href: index.html
---

```{r loading the dashboard package, message=FALSE}
library(flexdashboard)
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
```

```{r read dataset, message=FALSE}
airbnb <- read_csv("./data/nyc_airbnb.zip") %>%
  clean_names() %>%
  rename(.,boro = neighbourhood_group,
           rating = review_scores_location) %>%
  mutate(., rating = rating/2) %>%
  filter(.,boro == "Manhattan",
         room_type == "Entire home/apt",
         price > 100 & price < 400)
``` 

Column {data-width=650}
-----------------------------------------------------------------------

### plotly scatterplot
```{r}
airbnb %>%
  mutate(., hover_text = str_c("Price: $", price, '\nRating: ', rating)) %>%
  plot_ly(x = ~longitude, y = ~latitude, type = "scatter", mode = "markers",
          alpha = 0.5, 
          color = ~price,
          text = ~hover_text)
```

Column {data-width=450, .tabset}
-----------------------------------------------------------------------

### plotly barchart
```{r}
airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar")
```

### plotly boxplot
```{r}
common_neighborhoods <- airbnb %>% 
  count(neighbourhood, sort = TRUE) %>% 
  top_n(8) %>% 
  select(neighbourhood)

inner_join(airbnb, common_neighborhoods,
             by = "neighbourhood") %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box",
          colors = "Set2")
```